name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: /home/appvoiceofguru/public_html/testcpaneldeployment/
#      - uses: actions/checkout@master
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: app.voiceofguru.com
          username: appvoiceofguru
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 1980
          source: "app"
          target: "/home/appvoiceofguru/public_html/testcpaneldeployment/"
